### ISSUE TITLE
Cloudyweb assume the Game is always on the same machine

### ISSUE THREAD

**Issue by 9gix** [insert-coin/cloudyweb#24]
The IP Should be dynamically determined by the Game address. https://github.com/insert-coin/cloudyweb/blob/master/cloudygames/utils.py#L13

**Comment by gabriellaMT** [comment]
@9gix Actually, nope. This one should be hard-coded, but it is indeed not this IP.  This should be the IP used by CloudyWeb API (have you renamed this?) in CloudyGame Plugin, as I need to inform the plugin that a player will be joining. But as of now, we don't know this so I can not add the proper one.

**Comment by 9gix** [comment]
> Pls don't refer to CloudyWebAPI, unless you specifically refer to it and it is important to distinct the term. Use CloudyGamePlugin instead for this discussion.

This IP should be the CloudyGamePlugin IP addresses which I believe it is depends on what game it is and what is the ip address of that game. But I'm not sure what you mean by _"it is indeed not **this** IP"_. 

It is exactly because we won't know the IP address and it will never be fixed to one address in our code. Therefore it should be dynamically determined by the game address.

We don't know the game address, but the operator know this address, and it will be given by them from the CloudyPanel.

**Comment by 9gix** [comment]
@gabriellaMT this is an **urgent** fix. the CloudyWeb is unable to inform a join instruction to the game.

**Comment by gabriellaMT** [comment]
@9gix DOne

**Comment by gabriellaMT** [comment]
@9gix this issue can close alr
