### ISSUE TITLE
Renaming Repository to CloudyWeb

### ISSUE THREAD

**Issue by 9gix** [insert-coin/cloudyweb#26]
There has been some discussion to rename the repository into PascalCase instead of lowercase.

Most python repositories uses lowercase conventions, due to the fact that python uses lowercase for their module name too. However most of our projects are written in Windows which has PascalCase conventions such as, CloudyGamePlugin, and CloudyGameThinClient, provided we follow the others it will then be more consistent being CloudyWeb.

If any issues with the naming feel free to discuss it.

**Comment by ngsp94** [comment]
I only have issue with consistency across all the reports, code etc we have written. Basically if it's pascalcase, do the same for repo name, inside the code and in report + dev guide.

**Comment by gabriellaMT** [comment]
@9gix I think no objection as we put CloudyWeb inside the project report alr. Can execute this.

**Comment by 9gix** [comment]
Done with the renaming.
